spring:
  datasource:
    url: jdbc:postgresql://DBHOSTVALUE:5432/auditdb ## Replace the DBHOSTVALUE with appropriate value irrespective of internal or external DB ( internal DB eg: jdbc:postgresql://oes-db:5432/auditdb , external DB eg: jdbc:postgresql://database.cluster-rds.amazonaws.com:5432/auditdb)
    username: 'DBUSERNAME' ## Replace DBUSERNAME with appropriate value that is used for connecting
    password: 'DBPASSWORD' ## Replace DBPASSWORD with appropriate value that is used for connecting
logging:
    level:
      com.opsmx.auditservice: INFO
db:
  migration:
    enabled: true
message-broker:
  enabled: false
  endpoint:
    name: rabbitmq
standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv
feign:
  client:
    platformservice:
      name: platformservice
      url: http://oes-platform:8095
    auditclientservice:
      name: auditclientservice
      url: http://oes-audit-client:8098
    oes:
      url: http://oes-sapor:8085
    autopilot:
      url: http://oes-autopilot:8090
    visibilityservice:
      url: http://oes-visibility:8096
    dashboard:
      url: http://oes-dashboard:8094
