apiVersion: batch/v1
kind: Job
metadata:
  name: isd-yaml-update
  labels:
    app: byos
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - args:
            - |-

              for filename in /secret/*

              do

              variable=$(echo $filename | sed 's#/# #g' | awk '{print $2}')

              echo setting env $variable for $filename

              echo "export $variable=$(cat "$filename")" >> /tmp/environment

              done

              source /tmp/environment >/dev/null 2>&1

              cd /repo/

              export version="$version"

              chmod +x /repo/upgrade/isd-apply-yamls.sh

              /repo/upgrade/isd-apply-yamls.sh

          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          image: 'quay.io/opsmxpublic/helm-bash:v4'
          name: script
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
            - mountPath: /secret
              name: secret-volume
      initContainers:
        - args:
            - >-

              for secret in $(echo $secrets | sed "s/,/ /g")

              do

              echo getting $secret

              if ! kubectl -n "$namespace" get secret "$secret" >/dev/null 2>&1; then

              kubectl -n "$namespace" get secret "$secret"

                  echo "No secret $secret found, exiting"

                  exit 1

              fi
              
              kubectl -n "$namespace" get secret "$secret" -o jsonpath='{.data.*}' | base64 -d > /secret/"$secret"

              

              ls -ltr /secret/"$secret"

              done

          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
          - configMapRef:
              name: upgrade-inputcm
          image: 'quay.io/opsmxpublic/opsmx-custom-binaries:kubectl-spin-cli-git-bash-jq-yq'
          imagePullPolicy: IfNotPresent
          name: get-secrets
          volumeMounts:
            - mountPath: /secret
              name: secret-volume
            - mountPath: /repo
              name: repo-volume

        - args:
            - >-

              ls -ltr /secret/gittoken || { echo "failed cloning $url" ; exit 1; }

              #export branch="$branch"

              git clone https://"$username":"$(cat /secret/gittoken)"@"$url" -b "$branch" /repo

              echo "export version=$version" >> /repo/environment

              if [ $? != 0 ]

              then

                exit 1

              else

                ls -lrt /repo # Show the files cloned, as a success marker

              fi

          command:
            - /bin/bash
            - +x
            - '-c'
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          image: quay.io/opsmxpublic/helm-bash:v4-yq-jq
          name: git-clone
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
            - mountPath: /secret
              name: secret-volume
      restartPolicy: Never
      serviceAccountName: isd-install
      volumes:
        - emptyDir: {}
          name: secret-volume
        - emptyDir: {}
          name: repo-volume
