apiVersion: batch/v1
kind: Job
metadata:
  name: isd-post-helm-migrate
  labels:
    app: isd-install
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - args:
            - |-
              set +x
              source /repo/environment
              export source=${currentISDVersion}
              export spinnakersource=${spinnakerStorage}
              cd /repo/oes-data-migration-scripts/
              ls -ltra
              if [ "$source" == "3.12" ] && [ "$spinnakersource" == "sql" ]; then

                          echo "upgrading  v3.12 to v4.0.3"

                          #echo "python3 migration_v3.12.x_to_v4.0.x.py platformdb $host oesdb $host opsmx $host auditdb $host visibilitydb $host $port $pguser $pgpassword $oesuiurl $saporusername $ldappassword http://oes-sapor:8085 http://oes-audit:8097 sql $mysqlhost $mysqlusername $mysqlpassword true http://oes-platform:8095"

                          python3 migration_v3.12.x_to_v4.0.x.py platformdb $host oesdb $host opsmx $host auditdb $host visibilitydb $host $port $pguser $pgpassword $oesuiurl $saporusername $ldappassword http://oes-sapor:8085 http://oes-audit:8097 sql $mysqlhost 3306 $mysqlusername $mysqlpassword true http://oes-platform:8095

              elif [ "$source" == "3.12" ] && [ "$spinnakersource" == "redis" ]; then

                          echo "upgrading  v3.12 to v4.0.3"

                          #echo "python3 migration_v3.12.x_to_v4.0.x.py platformdb $host oesdb $host opsmx $host auditdb $host visibilitydb $host $port $pguser $pgpassword $oesuiurl $saporusername $ldappassword http://oes-sapor:8085 http://oes-audit:8097 redis "$release"-redis-master 6379 redisusername $redispassword true http://oes-platform:8095"

                          python3 migration_v3.12.x_to_v4.0.x.py platformdb $host oesdb $host opsmx $host auditdb $host visibilitydb $host $port $pguser $pgpassword $oesuiurl $saporusername $ldappassword http://oes-sapor:8085 http://oes-audit:8097 redis "$release"-redis-master 6379 redisusername $redispassword true http://oes-platform:8095

              else

                 echo "Some went wrong in mapping Pre DB Migration script"

              fi
                      CREATION_TIME=`date -u +"%d-%m-%Y-%H.%M.%S"`

                      mkdir -p /tmp/$CREATION_TIME/
                      echo $CREATION_TIME

                            ls -ltra /tmp/*.log

                            tar -czvf /tmp/OpsMx-Logs.tar.gz /tmp/*.log

                           curl --location --request PUT 'https://opsmx.jfrog.io/artifactory/opsmx-logs/posthelm/OpsMx-Logs-'"$CREATION_TIME"'.tar.gz' --header 'Authorization: Basic YW5vb3B0ZWo6T3BzTXhAMTIz' --header 'Content-Type: application/gzip' --data-binary '@/tmp/OpsMx-Logs-'"$CREATION_TIME"'.tar.gz'

                        if [ $? -eq 0 ]; then

                                          echo "Logs sucessfully pushed to https://opsmx.jfrog.io/artifactory/opsmx-logs/posthelm/OpsMx-Logs-$CREATION_TIME.tar.gz"
                              else
                                     echo "Failed to push logs to https://opsmx.jfrog.io/artifactory/opsmx-logs/posthelm/OpsMx-Logs-$CREATION_TIME.tar.gz"

                                     exit 1
                          fi
          command:
            - /bin/bash
            - +x
            - '-c'
          image: 'quay.io/opsmxpublic/ubi8-oes-platform-migration-script:v4.0.0'
          imagePullPolicy: Always
          name: exec-db-upgrade
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
      initContainers:
        - args:
            - |-

              export ns="${namespace}"

              source /home/opsmx/scripts/db_migration_script.sh

              ls -ltra  /repo/
          command:
            - /bin/bash
            - +x
            - '-c'
          image: 'quay.io/opsmxpublic/opsmx-custom-binaries:opsmx-isd-scripts-latest'
          imagePullPolicy: Always
          name: get-script
          envFrom:
            - configMapRef:
                name: upgrade-inputcm
          volumeMounts:
            - mountPath: /repo
              name: repo-volume
      restartPolicy: Never
      serviceAccountName: isd-install
      volumes:
        - emptyDir: {}
          name: repo-volume
