apiVersion: v1
data:
  url: github.com/ORGANIZATION_OR_USERNAME/GIT-REPO ## e.g github.com/ksrinimba/gitops-repo, url without the leading "https://", the "git-repo" in the documentation
  username: USERNAME_USED_FOR_AUTHENTICATION
  gitemail: YOUR_EMAIL@COMPANY.COM
  
  #####################################################################################################
  # Typically, there is no need to change the values below this line, please check the "nameaspace"
  #####################################################################################################
  branch: main         # Gitrepo branch, MUST be the default branch
  chartVersion: 4.0.8     # Helm Chart Version
  release: isd         # ISD helm-release version, default is oes
  currentISDVersion: "3.12"
  namespace: opsmx-isd # Namespace to install ISD, best not to change 
  secrets: gittoken,ldappassword,dbpassword,keystorepassword,rabbitmqpassword,saporpassword,redispassword,miniopassword,ldapconfigpassword
kind: ConfigMap
metadata:
  name: upgrade-inputcm
